"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environs
import dj_database_url
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environs.Env()
env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY", default=env.str("DJANGO_SECRET_KEY"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])  # replace * in production
# Ensure test client host allowed to prevent DisallowedHost during test runs
if ("test" in sys.argv or env.bool("ADD_TESTSERVER_HOST", default=True)) and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("testserver")

# CSRF trusted origins
_default_csrf_trusted = []
for _h in ALLOWED_HOSTS:
    if _h == "*":
        continue
    _default_csrf_trusted.append(f"http://{_h}")
    _default_csrf_trusted.append(f"https://{_h}")
    if _h in ("localhost", "127.0.0.1"):
        # Common local ports (nginx 8080, django 8001)
        _default_csrf_trusted.extend([
            f"http://{_h}:8080",
            f"http://{_h}:8001",
        ])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=_default_csrf_trusted)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "django_celery_results",
    "django_filters",
    # Local apps
    "auth.users",
    "auth.profiles",
    "apps.botapp",
    "apps.common",
    "apps.branch",
    # "apps.hr",  # DEPRECATED - functionality moved to apps.branch
    "apps.school",
    "apps.school.academic",
    "apps.school.classes",
    "apps.school.subjects",
    "apps.school.rooms",
    "apps.school.dashboard",
    "apps.school.students",
    "apps.school.finance",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware - eng yuqorida bo'lishi kerak
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.common.middlewares.request_logging.RequestLoggingMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

APPEND_SLASH = True


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env.bool("USE_SQLITE", default=False):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    database_url = env.str("DATABASE_URL", default=None)
    if database_url:
        DATABASES = {
            "default": dj_database_url.parse(database_url, conn_max_age=600, ssl_require=False)
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env("POSTGRES_DB"),
                "USER": env("POSTGRES_USER"),
                "PASSWORD": env("POSTGRES_PASSWORD"),
                "HOST": env("DB_HOST"),
                "PORT": env("DB_PORT"),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "uz"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR.joinpath("staticfiles")

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.joinpath("media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security hardening when not in DEBUG
if not DEBUG:
    SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", True)
    CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Proxy settings - development va production uchun
USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=True)
USE_X_FORWARDED_PORT = env.bool("USE_X_FORWARDED_PORT", default=True)

# DRF settings
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    "MAX_PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # You may enable browsable API in dev only if desired:
    # "DEFAULT_RENDERER_CLASSES": (
    #     "rest_framework.renderers.JSONRenderer",
    #     "rest_framework.renderers.BrowsableAPIRenderer" if DEBUG else "rest_framework.renderers.JSONRenderer",
    # ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Mendeleyev API",
    "DESCRIPTION": "RBAC asosida filiallar, foydalanuvchilar va bot integratsiyasi uchun REST API.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Optional additions
    "SCHEMA_PATH_PREFIX": "/api/v1",
}

# Custom user model
AUTH_USER_MODEL = "users.User"

# Logging configuration
LOG_LEVEL = env.str("LOG_LEVEL", default="INFO").upper()
LOG_FORMAT = env.str("LOG_FORMAT", default="text").lower()  # "json" | "text"
LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)

_json_formatter = {
    "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
}
_text_formatter = {
    "format": "%(asctime)s %(levelname)s [%(name)s:%(lineno)s] %(message)s",
}

_formatter = _json_formatter if LOG_FORMAT == "json" else _text_formatter

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": _formatter,
        "requests": _formatter,
    },
    "filters": {
        "production_error_filter": {
            "()": "apps.common.logging_handlers.ProductionErrorFilter",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
            "level": LOG_LEVEL,
        },
        "app_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            "when": "midnight",
            "backupCount": 14,
            "formatter": "default",
            "level": LOG_LEVEL,
        },
        "requests_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "requests.log"),
            "when": "midnight",
            "backupCount": 14,
            "formatter": "requests",
            "level": LOG_LEVEL,
        },
        "celery_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "celery.log"),
            "when": "midnight",
            "backupCount": 14,
            "formatter": "default",
            "level": LOG_LEVEL,
        },
        "telegram_admins": {
            "class": "apps.common.logging_handlers.TelegramAdminHandler",
            "level": "ERROR",
            "filters": ["production_error_filter"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "requests_file", "app_file", "telegram_admins"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_DB_LOG_LEVEL", "WARNING"),
            "propagate": False,
        },
        "apps": {
            "handlers": ["console", "app_file", "telegram_admins"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery": {
            "handlers": ["console", "celery_file", "telegram_admins"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Celery logging preferences
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# Error alerting toggle (default: enabled in production only)
ERROR_ALERTS_ENABLED = env.bool("ERROR_ALERTS_ENABLED", default=not DEBUG)

# Celery configuration
CELERY_BROKER_URL = env.str(
    "CELERY_BROKER_URL",
    default=f"redis://{env.str('REDIS_HOST', 'redis')}:{env.int('REDIS_PORT', 6379)}/{env.int('REDIS_DB', 0)}",
)

CELERY_RESULT_BACKEND = env.str(
    "CELERY_RESULT_BACKEND",
    default=f"redis://{env.str('REDIS_HOST', 'redis')}:{env.int('REDIS_PORT', 6379)}/{env.int('REDIS_DB', 0)}",
)

CELERY_TASK_TIME_LIMIT = env.int("CELERY_TASK_TIME_LIMIT", 60 * 10)  # hard limit 10m
CELERY_TASK_SOFT_TIME_LIMIT = env.int("CELERY_TASK_SOFT_TIME_LIMIT", 60 * 5)  # soft 5m
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ

# Celery Beat Schedule - periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'calculate-daily-salary-accrual': {
        'task': 'apps.branch.tasks.calculate_daily_salary_accrual',
        'schedule': crontab(hour=0, minute=0),  # Har kuni soat 00:00 da
        'options': {
            'expires': 3600,  # 1 soat ichida bajarilmasa bekor qilinsin
        }
    },
}

# OTP settings (Redis-backed)
OTP_CODE_TTL_SECONDS = env.int("OTP_CODE_TTL_SECONDS", 120)  # 2 minutes
OTP_REQUEST_COOLDOWN_SECONDS = env.int("OTP_REQUEST_COOLDOWN_SECONDS", 60)  # 1 minute
OTP_MAX_ATTEMPTS = env.int("OTP_MAX_ATTEMPTS", 5)
OTP_CODE_LENGTH = env.int("OTP_CODE_LENGTH", 6)
OTP_REDIS_PREFIX = env.str("OTP_REDIS_PREFIX", "otp")

# SimpleJWT lifetimes (can be tuned via env)
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int("JWT_ACCESS_MINUTES", 15)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env.int("JWT_REFRESH_DAYS", 30)),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": env.str("JWT_ALGORITHM", "HS256"),
    "SIGNING_KEY": SECRET_KEY,
}

# CORS settings for Next.js frontend
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",  # Next.js default port
        "http://127.0.0.1:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3001",
    ]
)

# Development: Allow all origins (only in DEBUG mode)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=True)
else:
    CORS_ALLOW_ALL_ORIGINS = False

# CORS headers
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
